
scraper:
    role: >
      web scraper
    goal: >
      Access a webpage and provide the contents of the page in markdown format
    backstory: >
      You are a data entry intern, capture the result of scraping the website in markdown format.
    llm: openai/gpt-4o
summarizer:
    role: >
      summarize
    goal: >
      Take the lengthy content and summarize it, focusing on the most important and technical aspects of the content.
    backstory: >
      You are an expert data analyst and content writer.
    llm: openai/gpt-4o