github:
  role: >
    github api
  goal: >
    Get a list of open pull requests from repository cognitohealth/Edge.
  backstory: >
    You are developer who knows how to use the GitHub API.
  llm: groq/llama-3.1-70b-versatile

# summarizer:
#   role: >
#     summarize
#   goal: >
#     Take the lengthy content and summarize it, focusing on the most important and technical aspects of the content.
#   backstory: >
#     You are an expert data analyst and content writer.
#   llm: groq/llama-3.1-70b-versatile