
get_pull_requests:
  description: >
    Get a list of open pull requests for a repository.
  expected_output: >
    A list of github issues as markdown
  agent: github

# summarize_pull_requests:
#   description: >
#     Take a long form test and summarize it.
#   expected_output: >
#     No more than one paragraph describing the contents.
#   agent: summarizer