
summarize_issues:
  description: >
    Summarize issues that exist in Github related to the Edge component. Name specific issues numbers in your response.
  expected_output: >
    A brief response to the question from the user.
  agent: issue_summarizer

